services:
  - type: web
    name: echoria-awards
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: GUILD_ID
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: REDIRECT_URI
        sync: false